insert into STATE VALUES (100,'INIT',1);
insert into STATE VALUES (200,'REQUESTED',1);
insert into STATE VALUES (300,'RESERVED',1);
insert into STATE VALUES (400,'REJECTED',1);
insert into STATE VALUES (500,'EXCHANGED',1);
insert into STATE VALUES (600,'CANCELLED',1);
insert into STATE VALUES (700,'RETURNED',1);
insert into STATE VALUES (800,'DAMAGED',1);
insert into STATE VALUES (900,'REVIEWED BY LENDER',1);
insert into STATE VALUES (901,'REVIEWED BY BORROWER',1);

insert into EDGE VALUES (0,100,200,'USER REQUESTED ITEM', '%B requested %L\'s item', 1);
insert into EDGE VALUES (1,200,300,'LENDER ACCEPTED REQUEST', '%L accepted %B\'s request', 1);
insert into EDGE VALUES (2,200,400,'LENDER REJECTED REQUEST', '%L rejected %B\'s request', 1);
insert into EDGE VALUES (3,300,500,'BORROWER CONFIRMED ITEM VIA TEXT MESSAGE', '%B confirmed and received %L\'s item',1);
insert into EDGE VALUES (4,300,600,'LENDER CANCELLED', '%L cancelled the transaction',1);
insert into EDGE VALUES (5,300,600,'BORROWER CANCELLED', '%B cancelled the transaction',1);
insert into EDGE VALUES (6,300,600,'HOLD FAILED','The credit card hold failed Transaction is cancelled',1);
insert into EDGE VALUES (7,500,700,'LENDER CONFIRMED RETURNED ITEM VIA TEXT MESSAGE','%B returned item to %L', 1);
insert into EDGE VALUES (8,500,800,'LENDER DID NOT SEND TEXT MESSAGE BY DUE DATE + SLACK TIME','%L never sent the confirmation text message',1);
insert into EDGE VALUES (9,500,800,'LENDER REPORTED ITEM AS DAMAGED','%L reported item as damaged',1);
insert into EDGE VALUES (10,500,800,'BORROWER REPORTED ITEM AS DAMAGED','%B reported item as damaged',1);
insert into EDGE VALUES (11,700,900,'LENDER SUBMITTED FEEDBACK','%L reviewed %B',1);
insert into EDGE VALUES (12,700,901,'BORROWER SUBMITTED FEEDBACK','%B reviewed %L',1);
insert into EDGE VALUES (13,900,901,'BORROWER SUBMITTED FEEDBACK','%B reviewed %L',1);
insert into EDGE VALUES (14,901,900,'LENDER SUBMITTED FEEDBACK','%L reviewed %B',1);

insert into REJECT_OPTIONS VALUES (0,'Scheduling issue',0);
insert into REJECT_OPTIONS VALUES (1,'Meeting issue',1);
insert into REJECT_OPTIONS VALUES (2,'Other',2);