ALTER TABLE USER ADD INDEX (ID, ACTIVE, EMAIL_ADDRESS);
ALTER TABLE USER ADD INDEX (EMAIL_ADDRESS);
ALTER TABLE USER ADD INDEX (PHONE_NUMBER);

ALTER TABLE ITEM ADD INDEX (ID);
ALTER TABLE ITEM ADD INDEX (LENDER_ID);

ALTER TABLE STATE ADD INDEX (ID);
ALTER TABLE STATE ADD INDEX (ID, ACTIVE);

ALTER TABLE EDGE ADD INDEX (ID, ACTIVE, STATE_B_ID); 
ALTER TABLE EDGE ADD INDEX (STATE_B_ID); 
ALTER TABLE EDGE ADD INDEX (STATE_A_ID, STATE_B_ID, ACTIVE); 

ALTER TABLE TRANSACTION ADD INDEX (ITEM_ID, ID);
ALTER TABLE TRANSACTION ADD INDEX (BORROWER_ID);

ALTER TABLE DETAIL ADD INDEX (ENTRY_DATE);
ALTER TABLE DETAIL ADD INDEX (TRANSACTION_ID, EDGE_ID, ENTRY_DATE);

ALTER TABLE ITEM_PICTURE ADD INDEX (ITEM_ID, PRIMARY_FLAG);

ALTER TABLE INVITE ADD INDEX (ID);
ALTER TABLE INVITE ADD INDEX (CODE);